package org.omg.PortableServer;


/**
* org/omg/PortableServer/LIFESPAN_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /build/openjdk-8-gyaYyR/openjdk-8-8u212-b03/src/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Friday, April 26, 2019 2:05:49 AM UTC
*/

public interface LIFESPAN_POLICY_ID
{

  /**
  	 * The value representing LIFESPAN_POLICY_ID.
  	 */
  public static final int value = (int)(17L);
}
